### ISSUE TITLE
Documentation for self-hosting

### ISSUE THREAD

**Issue by asheesh1996** [sipsorcery-org/signalrtc#1]
Hi, the current documentation in the docs folder is not clear, can you provide a better documentation for self-hosting

**Comment by sipsorcery** [comment]
This was originally a custom project for a single user. As it turned out they lost interest so I re-purposed for my own use.

Have you had a look at the sipsorcery.cloud page? If so, and you think it could be useful for you, I can certainly spend a bit of time to write a better document.

**Comment by asheesh1996** [comment]
Hi, I am trying to host this on my local ubuntu machine, I was able to clear off most of the Azure Auto DevOps, but I am struck on these build errors.
```
[01:25:19 INF] Starting signalrtc server version v0.0.38.0...
Unhandled exception. System.InvalidOperationException: Unable to resolve service for type 'System.Security.Cryptography.X509Certificates.X509Certificate2' while attempting to activate 'signalrtc.SIPHostedService'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateEnumerable(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.<>c__DisplayClass7_0.<GetCallSite>b__0(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at signalrtc.Program.Main(String[] args) in D:\Kaaya tech\Downloads\signalrtc-master\src\Program.cs:line 62 
```

**Comment by sipsorcery** [comment]
I don't recognise that error message. Are you using dotnet version 5?

I did test on my Ubuntu VM and spotted I was missing the sqlite file. I've added an empty file to the repo now. To use it you, as a minimum you need to add a SIP domain:

Adjust the `192.168.0.41` IP address to your own.

````
~/signalrtc/src$ sqlite3 AppData/sipassets.db
insert into SIPDomains values ('fed9be7f-0737-41a8-8d50-e3555dc9c970', '192.168.0.41', '[::1];127.0.0.1;localhost', CURRENT_TIMESTAMP);
````

After doing that the app starts on Ubuntu 18.04 for me:

````
~/signalrtc/src$ dotnet run
Building...
[21:19:24 INF] Starting signalrtc server version v0.0.38.0...
[21:19:25 DBG] Successfully loaded TLS certificate from certs/localhost.pfx, Common Name CN=localhost, has private key True.
[21:19:25 INF] User profile is available. Using '/home/admin/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
[21:19:26 DBG] SIPDomainManager adding domain: 192.168.0.41 with alias list [::1];127.0.0.1;localhost.
[21:19:26 INF] Creating key {aad5ee80-0d01-4154-a624-6555c2305f9b} with creation date 2021-07-22 21:19:26Z, activation date 2021-07-22 21:19:26Z, and expiration date 2021-10-20 21:19:26Z.
[21:19:26 WRN] No XML encryptor configured. Key {aad5ee80-0d01-4154-a624-6555c2305f9b} may be persisted to storage in unencrypted form.
[21:19:26 INF] Writing data to file '/home/admin/.aspnet/DataProtection-Keys/key-aad5ee80-0d01-4154-a624-6555c2305f9b.xml'.
[21:19:26 DBG] SIP hosted service starting...
[21:19:26 INF] SIP transport public contact hostname set to .
[21:19:26 INF] SIP transport public contact IPv4 set to .
[21:19:26 INF] SIP transport public contact IPv6 set to .
[21:19:26 INF] SIP transport private subnet 10.0.0.0/8.
[21:19:26 INF] SIP transport private subnet 192.168.0.0/24.
[21:19:26 INF] SIP TLS Channel created for tls:[::]:5061.
[21:19:26 INF] SIP TLS Channel ready for tls:[::]:5061 and certificate CN=localhost.
[21:19:26 DBG] SIP TLS Channel socket on tls:[::]:5061 accept connections thread started.
[21:19:26 DBG] CreateBoundUdpSocket attempting to create and bind UDP socket(s) on [::]:5060.
[21:19:26 DBG] CreateBoundUdpSocket successfully bound on [::]:5060, dual mode True.
[21:19:26 INF] SIP UDP Channel created for udp:[::]:5060.
[21:19:26 INF] SIP TCP Channel created for tcp:[::]:5060.
[21:19:26 DBG] SIP TCP Channel socket on tcp:[::]:5060 accept connections thread started.
[21:19:26 INF] SIP transport listening on tls:[::]:5061.
[21:19:26 INF] SIPRegistrarCore starting with 1 threads.
[21:19:26 INF] SIPB2BUserAgentCore starting with 1 threads.
[21:19:26 INF] SIPSubscriberCore starting with 1 threads.
[21:19:26 ERR] SIP DialPlan Manager could not load the default dialplan. Ensure a dialplan with the name of "default" exists.
[21:19:26 WRN] Overriding address(es) 'https://localhost:5001, http://localhost:5000'. Binding to endpoints defined in UseKestrel() instead.
[21:19:26 INF] Now listening on: http://[::]:5000
[21:19:26 INF] Now listening on: https://[::]:5001
[21:19:26 INF] Application started. Press Ctrl+C to shut down.
[21:19:26 INF] Hosting environment: Development
[21:19:26 INF] Content root path: /home/admin/signalrtc/src
````

**Comment by asheesh1996** [comment]
Hi, I tried the changes and deployed it on WSL2 on Ubuntu1.04 distro with dotnet5. I was able to successfully deploy it.
```
/mnt/d/Kaaya tech/Documents/Holosuit/Development/Git/signalrtc/src$ dotnet run

Welcome to .NET 5.0!
---------------------
SDK Version: 5.0.302

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
Building...
[13:12:26 INF] Starting signalrtc server version v0.0.38.0...
[13:12:26 DBG] Successfully loaded TLS certificate from certs/localhost.pfx, Common Name CN=localhost, has private key True.
[13:12:27 INF] User profile is available. Using '/home/goku/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
[13:12:28 DBG] SIPDomainManager adding domain:  172.29.191.255 with alias list [::1];127.0.0.1;localhost.
[13:12:28 INF] Creating key {27e757b9-9508-40b2-ae6f-0ff8c418e1e5} with creation date 2021-07-23 07:42:28Z, activation date 2021-07-23 07:42:28Z, and expiration date 2021-10-21 07:42:28Z.
[13:12:28 WRN] No XML encryptor configured. Key {27e757b9-9508-40b2-ae6f-0ff8c418e1e5} may be persisted to storage in unencrypted form.
[13:12:28 INF] Writing data to file '/home/goku/.aspnet/DataProtection-Keys/key-27e757b9-9508-40b2-ae6f-0ff8c418e1e5.xml'.
[13:12:28 DBG] SIP hosted service starting...
[13:12:28 INF] SIP transport public contact hostname set to .
[13:12:28 INF] SIP transport public contact IPv4 set to .
[13:12:28 INF] SIP transport public contact IPv6 set to .
[13:12:28 INF] SIP transport private subnet 10.0.0.0/8.
[13:12:28 INF] SIP transport private subnet 192.168.0.0/24.
[13:12:28 INF] SIP TLS Channel created for tls:[::]:5061.
[13:12:28 INF] SIP TLS Channel ready for tls:[::]:5061 and certificate CN=localhost.
[13:12:28 DBG] SIP TLS Channel socket on tls:[::]:5061 accept connections thread started.
[13:12:28 DBG] CreateBoundUdpSocket attempting to create and bind UDP socket(s) on [::]:5060.
[13:12:28 DBG] CreateBoundUdpSocket successfully bound on [::]:5060, dual mode True.
[13:12:28 INF] SIP UDP Channel created for udp:[::]:5060.
[13:12:28 INF] SIP TCP Channel created for tcp:[::]:5060.
[13:12:28 DBG] SIP TCP Channel socket on tcp:[::]:5060 accept connections thread started.
[13:12:28 INF] SIP transport listening on tls:[::]:5061.
[13:12:28 INF] SIPRegistrarCore starting with 1 threads.
[13:12:28 INF] SIPB2BUserAgentCore starting with 1 threads.
[13:12:28 INF] SIPSubscriberCore starting with 1 threads.
[13:12:28 ERR] SIP DialPlan Manager could not load the default dialplan. Ensure a dialplan with the name of "default" exists.
[13:12:28 WRN] Overriding address(es) 'https://localhost:5001, http://localhost:5000'. Binding to endpoints defined in UseKestrel() instead.
[13:12:28 INF] Now listening on: http://[::]:5000
[13:12:28 INF] Now listening on: https://[::]:5001
[13:12:28 INF] Application started. Press Ctrl+C to shut down.
[13:12:28 INF] Hosting environment: Development
[13:12:28 INF] Content root path: /mnt/d/Kaaya tech/Documents/Holosuit/Development/Git/signalrtc/src


[13:27:26 INF] Request starting HTTP/1.1 GET http://localhost:5000//con/bro - -
[13:27:26 INF] Request finished HTTP/1.1 GET http://localhost:5000//con/bro - - - 404 0 - 49.7926ms
```

But now when I am testing your WebRTCClient demo example with these configurations for signaling server
```
 private const string REST_SIGNALING_SERVER = "http://localhost:5000";
        private const string REST_SIGNALING_MY_USER = "console";
        private const string REST_SIGNALING_THEIR_USER = "unity";

```
I can see request logging in the signalrtc server
```
[13:12:28 INF] Hosting environment: Development
[13:12:28 INF] Content root path: /mnt/d/Kaaya tech/Documents/Holosuit/Development/Git/signalrtc/src


[13:27:26 INF] Request starting HTTP/1.1 GET http://localhost:5000//con/bro - -
[13:27:26 INF] Request finished HTTP/1.1 GET http://localhost:5000//con/bro - - - 404 0 - 49.7926ms
[13:36:24 INF] Request starting HTTP/1.1 GET http://localhost:5000//console/unity - -
[13:36:24 INF] Request finished HTTP/1.1 GET http://localhost:5000//console/unity - - - 404 0 - 1.2284ms
```
but its giving error in the WebRTCClient demo example 
```
PS D:\Git\sipsorcery\examples\WebRTCExamples\WebRTCClient> dotnet run
WebRTC Client Test Console
[13:36:24 DBG] CreateRtpSocket attempting to create and bind RTP socket(s) on [::]:0.
[13:36:24 DBG] CreateBoundUdpSocket attempting to create and bind UDP socket(s) on [::]:0.
[13:36:24 DBG] CreateBoundUdpSocket successfully bound on [::]:61977, dual mode True.
[13:36:24 DBG] Successfully bound RTP socket [::]:61977 (dual mode True).
[13:36:24 DBG] RTPChannel for [::]:61977 started.
[13:36:24 DBG] SCTP windows size for data receiver set at 218.
[13:36:25 DBG] SCTP creating DTLS based association, is DTLS client False, ID 5000:5000:61977.
[13:36:25 DBG] RTP ICE Channel discovered 1 local candidates.
[13:36:25 DBG] webrtc-rest starting receive task for server http://localhost:5000/, our ID console and their ID unity.
[13:36:25 ERR] Exception receiving webrtc signal. System.ApplicationException: Get request to REST server failed with response code NotFound.
   at SIPSorcery.Net.WebRTCRestSignalingPeer.ReceiveFromNSS(HttpClient httpClient, RTCPeerConnection pc, CancellationToken ct)
[13:36:25 DBG] webrtc-rest receive task exiting.

```
but its working with the hosting deployed 
        `private const string REST_SIGNALING_SERVER = "https://sipsorcery.cloud/api/webrtcsignal";
        `
and I am able to connect with UnityVideoSource Project
```
WebRTC Client Test Console
[13:45:54 DBG] CreateRtpSocket attempting to create and bind RTP socket(s) on [::]:0.
[13:45:54 DBG] CreateBoundUdpSocket attempting to create and bind UDP socket(s) on [::]:0.
[13:45:54 DBG] CreateBoundUdpSocket successfully bound on [::]:60728, dual mode True.
[13:45:54 DBG] Successfully bound RTP socket [::]:60728 (dual mode True).
[13:45:54 DBG] RTPChannel for [::]:60728 started.
[13:45:54 DBG] SCTP windows size for data receiver set at 218.
[13:45:54 DBG] SCTP creating DTLS based association, is DTLS client False, ID 5000:5000:60728.
[13:45:54 DBG] webrtc-rest starting receive task for server https://sipsorcery.cloud/api/webrtcsignal, our ID console and their ID unity.
[13:45:54 DBG] RTP ICE Channel discovered 1 local candidates.
[13:45:55 DBG] Got remote SDP, type offer.
[13:45:55 DBG] RTP ICE Channel remote credentials set.
[13:45:55 DBG] ICE connection state changed to checking.
[13:45:55 DBG] RTP ICE Channel received remote candidate: 2866 1 udp 659136 192.168.1.56 51761 typ host generation 0
[13:45:55 DBG] RTP ICE Channel received remote candidate: 2684 1 udp 659136 fe80::2552:e5f1:3b0e:7e46 51761 typ host generation 0
[13:45:55 WRN] Media announcement for audio omitted due to no reciprocal remote announcement.
[13:45:55 DBG] Adding new candidate pair to checklist for: udp:[::]:60728 (host)->udp:192.168.1.56:51761 (host)
[13:45:55 DBG] Adding new candidate pair to checklist for: udp:[::]:60728 (host)->udp:[fe80::2552:e5f1:3b0e:7e46]:51761 (host)
[13:45:55 DBG] ICE RTP channel sending connectivity check for udp:[::]:60728 (host)->udp:192.168.1.56:51761 (host) from [::]:60728 to 192.168.1.56:51761 (use candidate False).
[13:45:55 DBG] ICE RTP channel sending connectivity check for udp:[::]:60728 (host)->udp:[fe80::2552:e5f1:3b0e:7e46]:51761 (host) from [::]:60728 to [fe80::2552:e5f1:3b0e:7e46]:51761 (use candidate False).
[13:45:55 DBG] webrtc-rest PUT result for https://sipsorcery.cloud/api/webrtcsignal/sdp/console/unity OK.
[13:45:56 DBG] ICE RTP channel remote peer nominated entry from binding request: udp:192.168.1.56:51761 (host).
[13:45:56 INF] ICE RTP channel connected after 1874ms udp:[::]:60728 (host)->udp:192.168.1.56:51761 (host).
[13:45:56 DBG] ICE connection state changed to connected.
[13:45:56 DBG] Peer connection connected changed to connecting.
[13:45:56 INF] ICE connected to remote end point 192.168.1.56:51761.
[13:45:56 DBG] Starting DLS handshake with role active.
[13:45:56 DBG] RTCPeerConnection DoDtlsHandshake started.
[13:45:56 DBG] DTLS commencing handshake as client.
[13:45:56 DBG] RTCPeerConnection DTLS handshake result True, is handshake complete True.
[13:45:56 DBG] RTCPeerConnection remote certificate fingerprint matched expected value of FD:FA:10:B9:FD:D8:B2:80:C5:98:02:0E:FD:18:33:58:4C:37:77:BB:FC:BD:DD:0B:DA:8D:2B:CF:9B:AA:0C:F7 for sha-256.
[13:45:56 DBG] Secure context successfully set on RTPSession.
[13:45:56 DBG] Peer connection connected changed to connected.
[13:45:56 DBG] cancelling HTTP receive task.
[13:45:56 DBG] Set remote video track SSRC to 501596972.
[13:45:56 DBG] Video depacketisation codec set to VP8 for SSRC 501596972.
[13:45:56 WRN] VP8 decode attempt failed, Bitstream not supported by this decoder.
[13:45:56 WRN] VP8 decode attempt failed, Bitstream not supported by this decoder.
```

![image](https://user-images.githubusercontent.com/26667722/126755289-cf88fef5-4923-4e5b-9f42-67f1987aa261.png)

**Comment by sipsorcery** [comment]
You seem to have a typo in your URL `http://localhost:5000//con/bro`. It's not going to work with the '//' after `5000`.

But that's not the root cause of the problem.

The sipsorcery.cloud demo is set up in a specific way to suit my testing goals:

`vm1: signalrtc asp.net server` -> `vm2: Asterisk + FreeSWITCH + Janus + Kurento + other WebRTC test apps`

The `signalrtc` server is only doing the signalling. The audio/video comes from `vm2`.

Perhaps you're making things too difficult though. Is your goal to get a WebRTC stream from Unity? There are simpler WebRTC server examples to accomplish that. The `signalrtc` server is the most sophisticated, and most complicated, option.

**Comment by asheesh1996** [comment]
I tried version 5.0.3 where you have implemented node dss server , but with that implementatio also i am recieving following error 

```
PS C:\Users\Documents\Projects\sipsorcery\examples\WebRTCExamples\WebRTCClient> dotnet run
WebRTC Client Test Console
[22:37:21 DBG] CreateRtpSocket attempting to create and bind RTP socket(s) on [::]:0.
[22:37:22 DBG] CreateBoundUdpSocket attempting to create and bind UDP socket(s) on [::]:0.
[22:37:22 DBG] CreateBoundUdpSocket successfully bound on [::]:65231, dual mode True.
[22:37:22 DBG] Successfully bound RTP socket [::]:65231 (dual mode True).
[22:37:22 DBG] RTPChannel for [::]:65231 started.
[22:37:22 DBG] RTP ICE Channel discovered 5 local candidates.
[22:37:22 DBG] node-dss starting receive task for server http://127.0.0.1:3000/, our ID console and their ID unity.
[22:37:22 DBG] node-dss receive task exiting.
```
on unity side 
![image](https://user-images.githubusercontent.com/26667722/126876465-63dfb62a-ce65-4a22-bb25-f6d71ef584a8.png)


My aim is to send audio data using console app through audio encoders using https://github.com/atsushieno/libsoundio-sharp , and messages over datachannel

**Comment by sipsorcery** [comment]
> My aim is to send audio data using console app through audio encoders using https://github.com/atsushieno/libsoundio-sharp , and messages over datachannel

Could you explain this further? Do you want to get audio from Unity somehow and play it in a dotnet console app? What led you to this project? Was your idea to replace the use of `node-dss` in the [UnityVideoSource](https://github.com/sipsorcery-org/sipsorcery/tree/master/examples/WebRTCExamples/UnityVideoSource) example with the `signalrtc` application?

**Comment by asheesh1996** [comment]
> Could you explain this further? 


I am developing a cross platform dotnet app with one Peer running on Linux arm64 (connected with a microphone to send audio 
 and raw sensor data) and other peer running on windows (to receive the audio and raw sensor data), for that I need a signaling server 
>Do you want to get audio from Unity somehow and play it in a dotnet console app? What led you to this project? 

I was trying to test if I can compile my custom library with yours (both dotnet standard) and use in unity for testing.   

>Was your idea to replace the use of `node-dss` in the [UnityVideoSource](https://github.com/sipsorcery-org/sipsorcery/tree/master/examples/WebRTCExamples/UnityVideoSource) example with the `signalrtc` application?

Yes, first I tried with node-dss , but it didn't work, so I was trying if I can use signalrtc .

**Comment by sipsorcery** [comment]
>  one Peer running on Linux arm64 (connected with a microphone to send audio and raw sensor data) 

From my experiments it's hard to get audio devices working with .NET and linux/osx. If you solved this problem the rest should be easy.

> other peer running on windows (to receive the audio and raw sensor data)

That should be straight forward either using [SIPSorceryMedia.Windows](https://github.com/sipsorcery-org/SIPSorceryMedia.Windows) or another [NAudio](https://github.com/naudio/NAudio) wrapper.

> I was trying to test if I can compile my custom library with yours (both dotnet standard) and use in unity for testing.

Is Unity part of the plan for your app? Testing in Unity adds a big, complicated moving part to your testing. Even if you do plan on using Unity I'd generally recommend getting everything working without it as a first step.
 
> ...for that I need a signaling server Yes, first I tried with node-dss , but it didn't work, so I was trying if I can use signalrtc.

Ok, that's a sledge hammer for a nail. Signaling for WebRTC is not standardised. This has all the usual pros and cons; no complicated spec to implement but everyone can choose their own different way.

This 'signalrtc` app is not the answer for a simple WebRTC signaling option. There are a two helper classes in the main sipsorcery library that can be used for a rudimentary WebRTC signaling solution:

 - [WebRTCWebSocketPeer](https://github.com/sipsorcery-org/sipsorcery/blob/master/src/net/WebRTC/WebRTCWebSocketPeer.cs)
 - [WebRTCRestSignalingPeer](https://github.com/sipsorcery-org/sipsorcery/blob/master/src/net/WebRTC/WebRTCRestSignalingPeer.cs)

Both classes are used in some of the [WebRTC examples](https://github.com/sipsorcery-org/sipsorcery/tree/master/examples/WebRTCExamples). I'd recommend starting from there or even rolling your own signalling solution from scratch. All WebRTC requires is to exchange a few JSON messages between two peers. It can even be as simple as a single web socket send and receive in certain circumstances.
